services:
  streamlit:
    container_name: drug-release-analysis
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - ./drug_release_analysis:/app/drug_release_analysis
      - ./datasets:/app/datasets
    ports:
      - 8501:8501